import array
print("Array Directory:",dir(array))
print("Typecodes:",array.typecodes)
N=array.array('i',[1,2,3,4])
print("N:",N)
print("N Typecode:",N.typecode)
print("Item Size:",N.itemsize)
N.append(5)
print("After Append:",N)
print("Buffer Info:",N.buffer_info())
print("Byte Swap:",N.byteswap())
N=array.array('i',[1,2,3,4,5,1])
print("Count:",N.count(1))
N.extend([6,7,8,9])
print(N)
N.frombytes(b'\x08\x00\x00\x00')
print(N)
N.fromlist([3,2])
print("From List:",N)

string = array.array('u','Vikram')
print(string)
string.fromunicode(u'Mali')
print(string)
print("Index of 1:",N.index(1))
print("pop 2:",N.pop(2))
print("Remove 1:",N.remove(1))
N.reverse()
print("Reverse of N:",N)
print("To Bytes:",N.tobytes())

print("To List:",N.tolist())
print("To Unicode:",string.tounicode())

num1=array.array('i',[1,2,3])
num2=array.array('i',[9,10])
num3=num1+num2
print("Num3:",num3)
print("Num1 * 2:",num1*2)
print("Num3[2]:",num3[2])
num1=array.array('i',[1,2,3,4,5,6,7,8])
print(num1[1:8:2])
